name: Sa11y client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.6.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.1

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies (client)
        working-directory: ./sa11y-client
        run: pnpm install

      - name: Run linter
        working-directory: ./sa11y-client
        run: pnpm lint

      - name: Run unit tests
        working-directory: ./sa11y-client
        run: pnpm test

      - name: Install Playwright browsers
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: ./sa11y-client
        run: pnpm exec playwright install --with-deps

      - name: Run E2E tests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: ./sa11y-client
        env:
          VITE_API_URL: https://sa11y-api.ikigaya.dev
          VITE_CLIENT_URL: https://sa11y-app.ikigaya.dev
        run: pnpm test:e2e

      - name: Build
        working-directory: ./sa11y-client
        run: pnpm build